/**
 * Generates the bundle entry design-sync builds from.
 *
 * @devart/ui-react ships no root barrel (exports maps './*' -> dist/components/*),
 * so one has to be synthesized. Three files are produced, all generated and
 * gitignored, so the package's own metadata and published tarball are untouched:
 *
 *   dist/_ds-entry.js    explicit named re-exports of every runtime symbol.
 *                        NOT `export *`: the converter enumerates the bundle's
 *                        exports statically and star re-exports are invisible
 *                        to that scan (they yield 0 components).
 *   dist/_ds-entry.d.ts  the matching type surface. `export *` IS safe here,
 *                        because the type side is resolved by the TypeScript
 *                        checker, which does follow star re-exports.
 *   index.d.ts           design-sync resolves a package's type entry as
 *                        publishConfig.types -> types -> typings ->
 *                        <root>/index.d.ts. This package declares none of the
 *                        first three, so the root index.d.ts is what it looks for.
 *
 * Export names are read from the real runtime modules, so only value exports
 * are re-exported - re-exporting a type from a .js file throws at runtime.
 *
 * Run by cfg.buildCmd on every sync. Never hand-edit the generated files.
 */
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

const root = path.resolve(import.meta.dirname, '..');
const distDir = path.join(root, 'dist');
const compDir = path.join(distDir, 'components');

const modules = [];
for (const d of fs.readdirSync(compDir).sort()) {
  if (fs.existsSync(path.join(compDir, d, 'index.js'))) {
    modules.push(`./components/${d}/index.js`);
  }
}
modules.push('./lib/utils.js', './hooks/use-mobile.js');

const seen = new Map();
const lines = [
  '// AUTO-GENERATED by .design-sync/make-entry.mjs - do not edit.',
  '// Explicit named re-exports of every @devart/ui-react runtime symbol.',
  '',
];
const collisions = [];

for (const rel of modules) {
  const ns = await import(pathToFileURL(path.join(distDir, rel)).href);
  const parts = [];
  for (const n of Object.keys(ns).filter((k) => k !== 'default').sort()) {
    if (seen.has(n)) {
      // Keep the first owner's name and expose the later one under a prefixed
      // alias, so a collision is never silently dropped.
      const owner = path.basename(path.dirname(rel));
      const alias = `${owner.charAt(0).toLowerCase()}${owner.slice(1)}_${n}`;
      collisions.push(`${n} (${seen.get(n)} vs ${rel}) -> ${alias}`);
      parts.push(`${n} as ${alias}`);
      continue;
    }
    seen.set(n, rel);
    parts.push(n);
  }
  if (parts.length) lines.push(`export { ${parts.join(', ')} } from '${rel}';`);
}
lines.push('');
fs.writeFileSync(path.join(distDir, '_ds-entry.js'), lines.join('\n'));

const dts = [
  '// AUTO-GENERATED by .design-sync/make-entry.mjs - do not edit.',
  '',
  ...modules.map((rel) => `export * from '${rel.replace(/\.js$/, '')}';`),
  '',
];
fs.writeFileSync(path.join(distDir, '_ds-entry.d.ts'), dts.join('\n'));

fs.writeFileSync(
  path.join(root, 'index.d.ts'),
  [
    '// AUTO-GENERATED by .design-sync/make-entry.mjs - do not edit or commit.',
    '// Exists only so design-sync can resolve a root type entry.',
    "export * from './dist/_ds-entry';",
    '',
  ].join('\n')
);

console.log(
  `make-entry: ${modules.length} modules, ${seen.size} exports` +
    (collisions.length
      ? `, ${collisions.length} collision(s): ${collisions.join('; ')}`
      : '')
);
